### ISSUE TITLE
QCA9531's GPIO bitbang problem for cs_change

### ISSUE THREAD

**Issue by sheenhx** [Lora-net/lora_gateway#12] opened 2016-03-10 17:20 UTC
I successfully connect the IMST's lora gateway board to MT7628 with native SPI.

However, when it comes to the QCA9531 which doesn't port native SPI pins, it didn't work.

I tried SPI-GPIO bitbang, and it works for the other devices. But when I use the lora gateway,the CS pin behaves really wired.  

So I disabled cs_change then. It works!!

https://github.com/sheenhx/lora_gateway/commit/403f82099b04c4a5d286df5732d4ff2e01115df5

Is there anyone who can tell me why did this happen?

Environment: OpenWrt CC15.05  Kernel 3.18.27

**Comment by JiapengLi** [comment] 2016-03-31 03:20
Refer to #10

**Comment by mcoracin** [comment] 2016-04-14 15:38
Duplicate of #10, I close this one

**Closed by mcoracin** 2016-04-14 15:38 UTC
